#! /bin/sh
# /etc/init.d/plant
#

### BEGIN INIT INFO
# Provides:          plant
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     1 2 3 4 5 6
# Default-Stop:      0
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# setting usbwifi


# Some things that run always
touch /var/lock/plant

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    export PATH=$PATH:/usr/local/bin
	
	# Starting usb wifi
	if [$(exec lsusb | grep "148f:5370") == ""]; then
		echo '{"name":"","email":"","mode":"0","humidity":"60","MaxCistern":"17.5","minCistern":"3.5","addresses":"","Protocol":"WEP","ssid":"","key":""}' > /home/dmp/plant/settings.json
	else
		cd /home/dmp
		modprobe rt2800usb
		echo 148f 5370 | tee /sys/bus/usb/drivers/rt2800usb/new_id
		sleep 1
		ID=$(exec iwconfig | grep -o -P "wlan[0-9]*")
		echo $ID > /tmp/usbwifiID
		ifconfig $ID up
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		sleep 1
		Protocol=$(cat /home/dmp/plant/settings.json | grep -Po '(?<="Protocol":")[^"]*')
		ssid=$(cat /home/dmp/plant/settings.json | grep -Po '(?<="ssid":")[^"]*')
		key=$(cat /home/dmp/plant/settings.json | grep -Po '(?<="key":")[^"]*')
		if [ "$Protocol" == "WEP" ]; then
			iwconfig $ID key $key
			iwconfig $ID essid $ssid
		elif [ "$Protocol" == "WPA" ]; then
			wpa_passphrase $ssid $key > /etc/wpa_supplicant.conf
			wpa_supplicant -i $ID -D nl80211 -c /etc/wpa_supplicant.conf -B
		fi
		killall udhcpc
		sleep 1
		udhcpc -i $ID -b -t 10
	fi

	# Starting plant website
	sleep 1
	chmod 755 /home/dmp/plant/start.sh
	nohup /home/dmp/plant/start.sh


	if [$(exec lsusb | grep "fccf:a001") == ""]; then
		# Starting TFT display
		sleep 1
		chmod 755 /home/dmp/TFT_display/TFT_display
		cd /home/dmp/TFT_display
		./TFT_display
	else
		# Starting usbdisp
		modprobe rp_usbdisplay
		sleep 1
		modprobe -r rp_usbdisplay
		modprobe rp_usbdisplay
		sleep 1
		modprobe -r rp_usbdisplay
		modprobe rp_usbdisplay
		cp /home/dmp/rpusbdisp-master/drivers/linux-driver/xserver_conf/10-disp.conf /usr/share/X11/xorg.conf.d/

		sleep 3
		chmod 755 /home/dmp/UI_display/UI_display
		cd /home/dmp/UI_display/
		xinit ./UI_display
	fi
    ;;
  stop)
    echo "Stopping 86Duino Planter"
    echo "Stopping usbdisp"
    ;;
  *)
    echo "Usage: /etc/init.d/plant {start|stop}"

    exit 1
    ;;
esac

exit 0

