#!/bin/bash

echo checkWIFI


if [$(exec lsusb | grep "148f:5370") == ""]; then
		echo '{"name":"","email":"","mode":"0","humidity":"60","MaxCistern":"17.5","minCistern":"3.5","addresses":"","Protocol":"WEP","ssid":"","key":""}' > /home/dmp/plant/settings.json
else
	wget -q --tries=10 --timeout=10 --spider http://google.com
	if [[ $? -eq 0 ]]; then
		echo "Online"
	else
		echo "Offline"
		postsuper -d ALL
		cd /home/dmp
		modprobe rt2800usb
		echo 148f 5370 | tee /sys/bus/usb/drivers/rt2800usb/new_id
		sleep 1
		ID=$(exec iwconfig | grep -o -P "wlan[0-9]*")
		echo $ID > /tmp/usbwifiID
		ifconfig $ID up
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		killall wpa_supplicant
		sleep 1
		Protocol=$(cat /home/dmp/plant/settings.json | grep -Po '(?<="Protocol":")[^"]*')
		ssid=$(cat /home/dmp/plant/settings.json | grep -Po '(?<="ssid":")[^"]*')
		key=$(cat /home/dmp/plant/settings.json | grep -Po '(?<="key":")[^"]*')
		if [ "$Protocol" == "WEP" ]; then
			iwconfig $ID key $key
			iwconfig $ID essid $ssid
		elif [ "$Protocol" == "WPA" ]; then
			wpa_passphrase $ssid $key > /etc/wpa_supplicant.conf
			wpa_supplicant -i $ID -D nl80211 -c /etc/wpa_supplicant.conf -B
		fi
		killall udhcpc
		sleep 1
		udhcpc -i $ID -b -t 10
	fi
fi

